name: arc
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  - pyg
  - rdkit
  - scikit-learn
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - seaborn
  - networkx
  - jupyterlab
  - pip
  - pip:
      - notebook
